// Generate the package's CSS and TypeScript token APIs from its DTCG source.

import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { readFileSync, mkdirSync } from "node:fs";
import StyleDictionary from "style-dictionary";

const __dirname = dirname(fileURLToPath(import.meta.url));
const TOKENS_SRC = resolve(__dirname, "tokens/tokens.json");
const OUT_DIR = resolve(__dirname, "generated");

const raw = JSON.parse(readFileSync(TOKENS_SRC, "utf8"));
const THEMES = raw.$themes; // { dark:{...}, light:{color:{...}}, "high-contrast":{color:{...}} }

// --- name mapping: DTCG token path -> canonical CSS custom-property name ---------------------
// Most families map by rule; a handful of canonical names are hand-chosen (button->btn, the short
// dim names). This table reproduces the canonical tokens.css names exactly so the projection model
// is preserved (a different direction = a token swap, never a rename).
const EXPLICIT = {
  "component.color.button-primary-bg": "c-btn-primary-bg",
  "component.color.button-primary-text": "c-btn-primary-text",
  "component.color.button-danger-bg": "c-btn-danger-bg",
  "component.color.button-danger-text": "c-btn-danger-text",
  "component.color.focus-ring": "c-focus-ring",
  "component.color.chip-border": "c-chip-border",
  "component.color.chip-bg": "c-chip-bg",
  "component.color.agent-mark": "c-agent-mark",
  "component.color.rail-active-accent": "c-rail-active",
  "component.color.overlay-scrim": "overlay-scrim",
  "component.dimension.control-height": "control-h",
  "component.dimension.row-height": "row-h",
  "component.dimension.radius": "c-radius",
  "component.dimension.focus-width": "focus-width",
  "component.dimension.focus-offset": "focus-offset",
  "primitive.elevation.shadow.popover": "shadow-popover",
  "primitive.elevation.shadow.overlay": "shadow-overlay",
};

function cssVarName(dotted) {
  if (EXPLICIT[dotted]) return EXPLICIT[dotted];
  const p = dotted.split(".");
  // semantic.color.X -> X
  if (p[0] === "semantic" && p[1] === "color") return p[2];
  if (p[0] === "primitive") {
    if (p[1] === "dimension") return p[2]; // space-*, radius-*, hairline, border-2, target-min
    if (p[1] === "typography") {
      if (p[2] === "fontFamily") return `font-${p[3]}`;
      if (p[2] === "fontWeight") return `weight-${p[3]}`;
      if (p[2] === "fontSize") return `fs-${p[3]}`;
      if (p[2] === "lineHeight") return `lh-${p[3]}`;
    }
    if (p[1] === "duration") return `dur-${p[2]}`;
    if (p[1] === "easing") return `ease-${p[2]}`;
    if (p[1] === "zIndex") return `z-${p[2]}`;
  }
  return p.slice(1).join("-"); // fallback
}

// --- value formatting ----------------------------------------------------------------------------
const num = (n) => String(n).replace(/\.0$/, "");

function formatValue(token) {
  const v = token.value ?? token.$value;
  const type = token.$type ?? token.type;
  if (type === "fontFamily" || Array.isArray(v)) {
    if (type === "cubicBezier" || token.path?.includes("easing")) {
      return `cubic-bezier(${v.map(num).join(",")})`;
    }
    // fontFamily: quote multi-word / proper-noun families; leave generics/keywords bare.
    return v
      .map((f) => (/\s/.test(f) || /^[A-Z]/.test(f) ? `"${f}"` : f))
      .join(",");
  }
  if (type === "shadow" || (v && typeof v === "object" && "blur" in v)) {
    const s = v;
    const spread = s.spread && s.spread !== "0px" ? ` ${s.spread}` : "";
    return `${s.offsetX} ${s.offsetY} ${s.blur}${spread} ${s.color}`;
  }
  return String(v);
}

function originalRef(token) {
  const o = token.original?.value ?? token.original?.$value;
  return typeof o === "string" && o.startsWith("{") ? o.slice(1, -1) : null;
}

// --- the CSS format ------------------------------------------------------------------------------
function buildCss(dictionary) {
  const tokens = dictionary.allTokens;
  const byPrefix = (pfx) => tokens.filter((t) => t.path[0] === pfx);

  // primitive value map (dotted path -> resolved value) for resolving $themes overrides.
  const primMap = {};
  for (const t of byPrefix("primitive")) primMap[t.path.join(".")] = formatValue(t);

  const lines = [];
  lines.push(
    "/* GENERATED by build-tokens.mjs from tokens/tokens.json. DO NOT EDIT.",
    "   Re-skin = re-point the SEMANTIC aliases in tokens.json's $themes map; never edit here.",
    "   Components read ONLY semantic vars (--surface, --text-*, --focus-ring, ...). */",
    "",
  );

  // 1) :root primitives (everything EXCEPT raw colors, which are inlined into theme blocks).
  lines.push(":root {");
  for (const t of byPrefix("primitive")) {
    if (t.path[1] === "color") continue;
    if (t.path.join(".") === "primitive.elevation.shadow.none") continue;
    lines.push(`  --${cssVarName(t.path.join("."))}: ${formatValue(t)};`);
  }
  // component dimensions live in the :root block in canonical (compact defaults + focus geometry).
  for (const t of byPrefix("component")) {
    if (t.path[1] !== "dimension") continue;
    const ref = originalRef(t);
    const val = ref ? `var(--${cssVarName(ref)})` : formatValue(t);
    lines.push(`  --${cssVarName(t.path.join("."))}: ${val};`);
  }
  lines.push("}", "");

  // 2) theme blocks. dark is the default (resolved semantic tier) + the component bindings.
  const semantic = byPrefix("semantic");
  const componentColors = byPrefix("component").filter((t) => t.path[1] === "color");

  const emitTheme = (selector, colorScheme, resolveSemantic, includeComponent) => {
    lines.push(`${selector} {`);
    lines.push(`  color-scheme: ${colorScheme};`);
    for (const t of semantic) {
      lines.push(`  --${cssVarName(t.path.join("."))}: ${resolveSemantic(t)};`);
    }
    if (includeComponent) {
      lines.push("");
      for (const t of componentColors) {
        const ref = originalRef(t);
        const val = ref
          ? ref.startsWith("primitive")
            ? primMap[ref]
            : `var(--${cssVarName(ref)})`
          : formatValue(t);
        lines.push(`  --${cssVarName(t.path.join("."))}: ${val};`);
      }
    }
    lines.push("}", "");
  };

  // dark (default): semantic resolved value straight from SD.
  emitTheme(
    ':root,\n:root[data-theme="dark"]',
    "dark",
    (t) => formatValue(t),
    true,
  );

  // light / high-contrast: re-resolve each semantic alias through the $themes override map.
  for (const name of ["light", "high-contrast"]) {
    const overrides = THEMES[name]?.color ?? {};
    const scheme = name === "light" ? "light" : "dark";
    emitTheme(
      `:root[data-theme="${name}"]`,
      scheme,
      (t) => {
        const key = t.path[2];
        const ov = overrides[key];
        if (ov) {
          const ref = ov.startsWith("{") ? ov.slice(1, -1) : ov;
          return primMap[ref] ?? ref;
        }
        return formatValue(t); // unlisted alias inherits the default
      },
      false,
    );
  }

  // 3) foundation rules — the hand-authored, non-tokenizable layer (focus-visible geometry,
  //    forced-colors + reduced-motion fallbacks). Kept verbatim from the canonical tokens.css so
  //    the generated stylesheet is directly consumable; it carries no token VALUES.
  lines.push(FOUNDATION_RULES);
  return lines.join("\n");
}

const FOUNDATION_RULES = `/* ============================================================================
   FOUNDATION RULES (inherited by every component; not token values)
   ============================================================================ */
*{box-sizing:border-box}

/* Shared focus-ring treatment for interactive elements. */
:where(a,button,input,select,textarea,[tabindex],
       [role="button"],[role="tab"],[role="option"],
       [role="menuitem"],[role="checkbox"],[role="switch"]):focus-visible{
  outline:var(--focus-width) solid var(--c-focus-ring, var(--focus-ring));
  outline-offset:var(--focus-offset);
  border-radius:var(--radius-1);
}

/* High-contrast / forced-colors: never lose focus or status meaning. */
@media (forced-colors: active){
  :where(a,button,input,select,textarea,[tabindex],
         [role="button"],[role="tab"],[role="option"]):focus-visible{
    outline:var(--border-2) solid Highlight;
    outline-offset:var(--focus-offset);
  }
  :where([data-elevated],[role="dialog"],[role="menu"]){border:1px solid CanvasText}
}

/* Reduced motion is a first-class spelling, not a removal (R-12 L4). */
@media (prefers-reduced-motion: reduce){
  :root{
    --dur-micro:0ms; --dur-fast:0ms; --dur-base:0ms; --dur-deliberate:0ms;
  }
  *{animation-duration:0ms !important; transition-duration:0ms !important; scroll-behavior:auto !important}
}
`;

// --- the TS format -------------------------------------------------------------------------------
function buildTs(dictionary) {
  const tokens = dictionary.allTokens;
  const byPrefix = (pfx) => tokens.filter((t) => t.path[0] === pfx);
  const primMap = {};
  for (const t of byPrefix("primitive")) primMap[t.path.join(".")] = formatValue(t);

  const semantic = byPrefix("semantic").filter((t) => t.path[1] === "color");
  const zIndex = byPrefix("primitive").filter((t) => t.path[1] === "zIndex");

  const resolveForTheme = (t, name) => {
    if (name === "dark") return formatValue(t);
    const ov = THEMES[name]?.color?.[t.path[2]];
    if (ov) {
      const ref = ov.startsWith("{") ? ov.slice(1, -1) : ov;
      return primMap[ref] ?? ref;
    }
    return formatValue(t);
  };

  const out = [];
  out.push(
    "// GENERATED by build-tokens.mjs from tokens/tokens.json.",
    "// DO NOT EDIT. The CSS custom properties in tokens.css are the runtime; these TS constants",
    "// are for the rare cases CSS vars can't reach (z-index in JS, canvas/chart colors, the",
    "// native <meta name=theme-color>, theme enumeration).",
    "",
  );

  // z-index — JS needs the numeric value (e.g. imperative portal stacking).
  out.push("export const Z_INDEX = {");
  for (const t of zIndex) out.push(`  ${t.path[2]}: ${formatValue(t)},`);
  out.push("} as const;");
  out.push("export type ZLayer = keyof typeof Z_INDEX;", "");

  // semantic color var() references — the typed surface components consume.
  out.push("export const semanticColor = {");
  for (const t of semantic) out.push(`  "${t.path[2]}": "var(--${t.path[2]})",`);
  out.push("} as const;");
  out.push("export type SemanticColor = keyof typeof semanticColor;", "");

  // themes + resolved hex per theme (CSS-can't-reach cases).
  out.push('export const THEMES = ["dark", "light", "high-contrast"] as const;');
  out.push("export type ThemeName = (typeof THEMES)[number];", "");
  out.push("export const themeColors = {");
  for (const name of ["dark", "light", "high-contrast"]) {
    out.push(`  "${name}": {`);
    for (const t of semantic)
      out.push(`    "${t.path[2]}": "${resolveForTheme(t, name)}",`);
    out.push("  },");
  }
  out.push("} as const;", "");
  return out.join("\n");
}

// --- run -----------------------------------------------------------------------------------------
StyleDictionary.registerFormat({ name: "myelin/css", format: ({ dictionary }) => buildCss(dictionary) });
StyleDictionary.registerFormat({ name: "myelin/ts", format: ({ dictionary }) => buildTs(dictionary) });

mkdirSync(OUT_DIR, { recursive: true });

const sd = new StyleDictionary({
  usesDtcg: true,
  source: [TOKENS_SRC],
  // Our custom format keys off each token's `path` directly (not SD's default name transform), so
  // SD's internal name-collision heuristic is irrelevant here — silence its (benign) warning.
  log: { warnings: "disabled" },
  platforms: {
    web: {
      buildPath: "generated/",
      files: [
        { destination: "tokens.css", format: "myelin/css" },
        { destination: "tokens.ts", format: "myelin/ts" },
      ],
    },
  },
});

await sd.buildAllPlatforms();
console.log("tokens: built generated/tokens.css + generated/tokens.ts from", TOKENS_SRC);
