//! # The production-graph ABSENCE baseline ratchet (MR-004) — the evidence-integrity skeleton.
//!
//! This test wires the three production-graph absence scanners
//! ([`myelin_lints::production_graph`]) two ways, in the same shape as the twelve architecture
//! lints' `fixture_matrix.rs` + `workspace_clean.rs`:
//!
//!   1. **The fixture matrix** — each scanner's RED fixture produces ≥1 violation (it bites) and
//!      its GREEN fixture produces 0 (it does not over-reject), and each red trips EXACTLY its own
//!      scanner (cross-isolation). This is the fixtures half (deterministic, hermetic).
//!
//!   2. **The baseline ratchet** — the scanners are run over the REAL `crates/*/src` tree and the
//!      violation set is asserted to EQUAL a committed baseline manifest of the CURRENT known
//!      shortcut sites — NOT zero. The real tree VIOLATES all three scanners by design (that is the
//!      whole point: they document the live shortcuts MR-009/MR-012/MR-013 will remove), so these
//!      three are deliberately NOT in `all_twelve()` / the `workspace_clean` zero-violation gate
//!      (adding them there would turn the build red). The ratchet can only TIGHTEN toward zero: it
//!      FAILS LOUDLY if (a) a NEW violation appears anywhere in scope, or (b) a baseline entry is
//!      fixed/moved but not removed from the manifest. That is the mechanism by which MR-009/012/013
//!      prove they actually removed the shortcut (EI-01 §5 — an uncommitted gate is no gate).
//!
//! ## Scope of each scanner's gate (documented, LOUD — never a silent skip; EI-01 §4)
//! Like `workspace_clean.rs`'s named exclusions, each scanner's WORKSPACE gate is scoped to where
//! its census-named shortcuts live, and the scope is named here, not hidden:
//!   - `no-structural-crypto-in-prod` → ALL crates. The `Structural*` mock-crypto types are few and
//!     the scanner is precise (construction-only, `#[cfg(test)]`-excluded), so a workspace-wide gate
//!     is clean and catches any prod construction wherever it appears.
//!   - `no-in-memory-durable-store` → the SPINE/SUBSTRATE crates (`myelin-identity-service`,
//!     `myelin-events`, `myelin-control-plane`, `myelin-storage`). Every census-named scanner-#2
//!     site lives here, and these are the crates MR-007/008/009 (the spine durable-persistence MRs
//!     this skeleton verifies) act on. Product-subsystem in-memory stores (chat/knowledge/issues/
//!     notif/agent/git/ci) ride their OWN subsystem tracks (census Section B2), not this SPINE
//!     scanner — scoping here keeps the baseline mapped to spine shortcuts and avoids flagging
//!     subsystem stores this MR does not own (scope discipline).
//!   - `no-bare-tenant-pool` → `myelin-storage` (the crate that owns the tenant RLS / pool
//!     primitive; census SI-005 = `pg.rs`). MR-013 (P-531) hardens THIS live pool.
//!
//! ## THE COMMITTED BASELINE MANIFEST (the current known-shortcut sites + their fixing MR/SI)
//! Each entry: `crate/path/file.rs:line — <scanner> — removed by MR-0XX (SI-0YY / P-NNN)`.
//! Generated by running the scanners over the real tree at MR-004. The line numbers are pinned;
//! when MR-009/012/013 edit a target file they update/remove its entry (the ratchet tightens).
//!
//! ### `no-structural-crypto-in-prod` (5) — removed by MR-010/011/012 (P-526/527/528)
//! - `myelin-identity-service/src/authenticate.rs:289`  — `StructuralVerifier` default (SI-004)
//! - `myelin-identity-service/src/machine_auth.rs:406`  — `StructuralTokenVerifier` default (SI-002)
//! - `myelin-identity-service/src/mint.rs:253`          — `StructuralTokenSigner` default (SI-003)
//! - `myelin-identity-service/src/mint.rs:265`          — `StructuralTokenSigner` w/tuples (SI-003)
//! - `myelin-ci-controlplane/src/residency_drill.rs:444`— `StructuralAttestationVerifier` (SI-001/attestation floor, P-527)
//!
//! ### `no-in-memory-durable-store` (17) — removed by the spine durable-persistence MRs (P-522/523)
//! - `myelin-identity-service/src/principal_store.rs:289` — `PrincipalStore` (SI-018). MR-007 ADDED
//!   the durable `with_pg` PG path (proven live: `integration_mr007_identity_durable`) but the
//!   `Memory(Arc<Mutex<Inner>>)` variant is still the always-compiled default (the `Pg` variant is
//!   `#[cfg(feature="integration")]`) and nothing wires it yet — so the in-memory store is STILL the
//!   production default. The scanner now FOLLOWS the backend enum (MR-007 fix) and still fires.
//!   Removed when production wires `with_pg` as the non-optional default (MR-009 / route MRs).
//! - `myelin-identity-service/src/tuple_store.rs:220`     — `TupleStore` (SI-019), same MR-007 status.
//! - `myelin-identity-service/src/revocation.rs:193`      — `RevocationStore` (SI-019/SI-020). MR-008
//!   ADDED the durable `with_pg` path (proven live incl. expiry-across-restart:
//!   `integration_mr008_revocation_durable`); `Memory` variant still the default → enum-following
//!   scanner still fires. Removed at MR-009 wiring.
//! - `myelin-identity-service/src/machine_auth.rs:347`    — `S7Denylist` (SI-020), the auth revocation
//!   CONSULT stub (no durable backing — loses revocations on restart). MR-008 added it to the named
//!   holders; the fix is routing `CapabilityAuthenticator` to the durable `RevocationStore` (MR-009).
//! - `myelin-identity-service/src/pseudonym_store.rs:191` — `PseudonymStore` (S2) in-mem (SI-018 cluster; MR-007/009)
//! - `myelin-identity-service/src/pseudonym_erase.rs:268` — `PseudonymErasureLedger` in-mem via the
//!     `type LedgerByPartition = BTreeMap<…>` ALIAS (alias false-negative closed; census 10.8; MR-007/009)
//! - `myelin-events/src/outbox.rs:230`                    — `OutboxStore` in-mem (SI-007; events durable MR, P-522/523)
//! - `myelin-events/src/dedup.rs:141`                     — `DedupLedger` (SI-023). MR-023 ADDED the
//!   durable `DurableDedup` PG seam (`DedupLedger::durable`, backing
//!   `myelin_storage::events_durable::DurableDedupBacking`, proven live:
//!   `integration_mr023_events_serve`) but the `Memory(Arc<Mutex<HashSet>>)` backend variant is
//!   still the always-compiled default — so the enum-following scanner STILL fires (supplemented,
//!   not removed). Removed when production wires `durable` as the non-optional default (MR-009 /
//!   route MRs), the same status as MR-007/008's principal/tuple/revocation entries.
//! - `myelin-events/src/reerase.rs:102`                   — `BusErasureLedger` in-mem (SI-039; GDPR/events durable MR)
//! - `myelin-control-plane/src/registry.rs:111`          — `Registry` placement in-mem (SI-011; cp durable MR)
//! - `myelin-control-plane/src/cross_cell_bridge.rs:244` — `CellResolverRegistry` in-mem (SI-052; cp/multi-cell MR)
//! - `myelin-control-plane/src/placement_of.rs:223`      — `MisrouteAudit` `Arc<Mutex<Vec<…>>>` audit sink (SI-028; cp durable MR)
//! - `myelin-storage/src/kms.rs:470`                      — `KmsEngine` root/KEKs in-mem (SI-006; MR-009 / Tier-4 P-524)
//! - `myelin-storage/src/reserve_settle.rs:283`          — `CostLedger` reserve/settle in-mem (SI-021 cluster; MR-007/009)
//! - `myelin-storage/src/restore_verify.rs:175`          — `ErasureLedger` restore-verify in-mem (SI-036 cluster; P-530)
//! - `myelin-storage/src/reerase.rs:156`                  — `InMemoryPostPitLedger` `records: Vec<…>` (Vec false-negative closed; P-ST-14 / P-522/523)
//! - `myelin-storage/src/blob.rs:362`                     — `FsBlobStore` `Mutex<HashMap<…, Vec<u8>>>` IN-MEMORY (no `fs::write`); byte backing is the Git/backup track (P-ST-30; SI-014/015/029)
//!
//! ### Role-suffix BLIND SPOT (documented coverage boundary — NOT yet gated; verifier MR-004 review)
//! Scanner #2 keys on the durable-role NAME suffix (`Store`/`Registry`/`Outbox`/`Ledger`) + a small
//! named-holder list (`KmsEngine`, `MisrouteAudit`). Census persistence shortcuts whose struct has
//! NEITHER are INVISIBLE to it — this baseline covers the role-suffix representative PER ORGAN, NOT
//! the full census persistence set. Known-uncovered (each rides a not-yet-authored persistence MR
//! that MUST extend this scanner — add the type to `NAMED_DURABLE_HOLDERS` or widen the suffix set —
//! when it lands; see the matching note in `production_graph.rs`):
//!   - `S7Denylist` (SI-020, identity revocation hot-set) · `Consumer` (SI-024, events cursor/lag)
//!   - `Firehose` (SI-037, live transport) · `InMemoryShredder` (SI-038, GDPR shred) ·
//!     `OltpPool` (SI-021, OLTP permit pool) · `PlacementService` stickiness (SI-026, control-plane)
//! A future "we made the bus / control-plane durable" claim is therefore only PARTIALLY gated until
//! that MR extends the scanner — this note exists so that gap is not silently relied upon.
//!
//! ### `no-bare-tenant-pool` (2) — removed by MR-013 (P-531)
//! - `myelin-storage/src/pg.rs:413` — session-scoped `set_config('myelin.tenant_id', $1, false)` (SI-005)
//! - `myelin-storage/src/pg.rs:150` — bare raw-pool hatch `PgStore::pool() -> &PgPool` (SI-005)

use myelin_lints::production_graph::{
    no_bare_tenant_pool, no_in_memory_durable_store, no_structural_crypto_in_prod,
    production_graph_absence_scanners, PRODUCTION_GRAPH_ABSENCE_SCANNERS,
};
use myelin_lints::{Lint, LintId};
use std::path::{Path, PathBuf};

// ================================================================================================
// The fixture matrix (the fixtures half — each scanner red-bites + green-admits + cross-isolation).
// ================================================================================================

const FIXTURES_DIR: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/fixtures");

fn read_fixture(name: &str) -> String {
    let path = format!("{FIXTURES_DIR}/{name}");
    std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("missing fixture {path}: {e}"))
}

struct Row {
    lint: fn() -> Lint,
    id: LintId,
    red: &'static str,
    green: &'static str,
}

fn matrix() -> Vec<Row> {
    vec![
        Row {
            lint: no_structural_crypto_in_prod,
            id: LintId("no-structural-crypto-in-prod"),
            red: "no_structural_crypto_in_prod.red.rs.txt",
            green: "no_structural_crypto_in_prod.green.rs.txt",
        },
        Row {
            lint: no_in_memory_durable_store,
            id: LintId("no-in-memory-durable-store"),
            red: "no_in_memory_durable_store.red.rs.txt",
            green: "no_in_memory_durable_store.green.rs.txt",
        },
        Row {
            lint: no_bare_tenant_pool,
            id: LintId("no-bare-tenant-pool"),
            red: "no_bare_tenant_pool.red.rs.txt",
            green: "no_bare_tenant_pool.green.rs.txt",
        },
    ]
}

#[test]
fn the_matrix_covers_exactly_the_three_scanners() {
    let rows = matrix();
    assert_eq!(rows.len(), 3, "the matrix must cover all three absence scanners");
    let ids: Vec<LintId> = rows.iter().map(|r| r.id).collect();
    assert_eq!(ids, PRODUCTION_GRAPH_ABSENCE_SCANNERS.to_vec());
}

#[test]
fn every_red_fixture_bites() {
    for row in matrix() {
        let lint = (row.lint)();
        let v = lint.run(&read_fixture(row.red));
        assert!(
            !v.is_empty(),
            "scanner `{}` MUST reject its red fixture `{}`, but found 0 violations",
            row.id,
            row.red
        );
        assert!(
            v.iter().all(|x| x.lint == row.id),
            "scanner `{}` red-fixture violations must all carry its own id",
            row.id
        );
    }
}

#[test]
fn every_green_fixture_is_admitted() {
    for row in matrix() {
        let lint = (row.lint)();
        let v = lint.run(&read_fixture(row.green));
        assert!(
            v.is_empty(),
            "scanner `{}` MUST admit its green fixture `{}`, but found: {:?}",
            row.id,
            row.green,
            v
        );
    }
}

#[test]
fn each_red_fixture_trips_exactly_its_own_scanner() {
    // Cross-isolation among the three: a red fixture for scanner X is caught by X and by neither
    // of the other two (so the baseline-ratchet attributes each violation to the right scanner).
    let all = production_graph_absence_scanners();
    for row in matrix() {
        let red = read_fixture(row.red);
        let firing: Vec<LintId> = all
            .iter()
            .filter(|l| !l.run(&red).is_empty())
            .map(|l| l.id)
            .collect();
        assert_eq!(
            firing,
            vec![row.id],
            "red fixture `{}` must trip exactly `{}`, but tripped: {:?}",
            row.red,
            row.id,
            firing
        );
    }
}

// ================================================================================================
// The baseline ratchet (the live half — the scanners over the real tree vs the committed baseline).
// ================================================================================================

/// One scanner's workspace gate: its constructor + its scope (path substrings of the crates it
/// gates) — the documented, LOUD per-scanner scope (see the module docs).
struct Gate {
    lint: fn() -> Lint,
    scope: &'static [&'static str],
}

const SPINE: &[&str] = &[
    "crates/myelin-identity-service/",
    "crates/myelin-events/",
    "crates/myelin-control-plane/",
    "crates/myelin-storage/",
];

fn gates() -> Vec<Gate> {
    vec![
        Gate {
            lint: no_structural_crypto_in_prod,
            scope: &["crates/"], // ALL crates (precise, construction-only scanner).
        },
        Gate {
            lint: no_in_memory_durable_store,
            scope: SPINE, // the spine/substrate crates (census-named sites; MR-007/008/009).
        },
        Gate {
            lint: no_bare_tenant_pool,
            scope: &["crates/myelin-storage/"], // the tenant-pool primitive owner (SI-005; MR-013).
        },
    ]
}

/// THE COMMITTED BASELINE: `(scanner id, crate-relative path, 1-based line)`. Sorted. Mirrors the
/// annotated manifest in the module docs above. The ratchet asserts the live firing set EQUALS this.
const BASELINE: &[(&str, &str, usize)] = &[
    // ---- no-structural-crypto-in-prod (5) — MR-010/011/012 (P-526/527/528) ----
    (
        "no-structural-crypto-in-prod",
        "crates/myelin-ci-controlplane/src/residency_drill.rs",
        444,
    ),
    (
        "no-structural-crypto-in-prod",
        "crates/myelin-identity-service/src/authenticate.rs",
        289,
    ),
    (
        "no-structural-crypto-in-prod",
        "crates/myelin-identity-service/src/machine_auth.rs",
        406,
    ),
    (
        "no-structural-crypto-in-prod",
        "crates/myelin-identity-service/src/mint.rs",
        253,
    ),
    (
        "no-structural-crypto-in-prod",
        "crates/myelin-identity-service/src/mint.rs",
        265,
    ),
    // ---- no-in-memory-durable-store (13 here + 4 closed-false-negatives below = 17) ----
    //      spine durable-persistence MRs (P-522/523); MR-008 added machine_auth.rs:347 (S7Denylist).
    (
        "no-in-memory-durable-store",
        "crates/myelin-control-plane/src/cross_cell_bridge.rs",
        244,
    ),
    // MR-024 (SI-011) ADDED the durable PG path for the placement registry: the `cell` +
    // `tenant_placement` tables (frozen contract-12.3) + the HARD placement invariant as a REAL DB
    // TRIGGER (`myelin_storage::placement_durable`) + the `Pg | Memory` backend enum binding
    // (`myelin_control_plane::registry_durable::DurablePlacementRegistry::with_pg`), PROVEN durable +
    // trigger-enforced against live PG (`integration_mr024_placement_durable`). Same status as the
    // identity stores: the in-memory `Registry` (the `Memory` arm) is still the always-compiled
    // DEFAULT and nothing wires the Pg arm in production yet (the Pg arm is behind
    // `#[cfg(feature="integration")]`), so the in-memory store is still the production-graph default
    // and this entry STILL fires here — honestly, SUPPLEMENTED not removed. Removed when production
    // boot wires the durable Pg arm as the non-optional default (MR-009).
    (
        "no-in-memory-durable-store",
        "crates/myelin-control-plane/src/registry.rs",
        111,
    ),
    (
        "no-in-memory-durable-store",
        "crates/myelin-events/src/dedup.rs",
        141,
    ),
    (
        "no-in-memory-durable-store",
        "crates/myelin-events/src/outbox.rs",
        230,
    ),
    (
        "no-in-memory-durable-store",
        "crates/myelin-events/src/reerase.rs",
        102,
    ),
    // MR-007 (SI-018/019) ADDED the durable PG path (`with_pg` over
    // `myelin_storage::Durable{Principal,Tuple}Backing` + the MR-022 `with_tenant_tx` convention) and
    // PROVED it durable + tenant-isolated against live PG (`integration_mr007_identity_durable`). But
    // the in-memory store is NOT yet removed — only SUPPLEMENTED: the `Memory(Arc<Mutex<Inner>>)`
    // variant still holds the collection, it is the ALWAYS-compiled default (the `Pg` variant is
    // behind `#[cfg(feature="integration")]`), and NO production code wires either store yet. So the
    // in-memory store is still the production-graph DEFAULT. The scanner now FOLLOWS the backend enum
    // (the MR-007 enum-following fix) and STILL fires here — honestly. These two are REMOVED when
    // production wires the durable `with_pg` path as the non-optional default (MR-009 / route MRs).
    (
        "no-in-memory-durable-store",
        "crates/myelin-identity-service/src/principal_store.rs",
        289,
    ),
    (
        "no-in-memory-durable-store",
        "crates/myelin-identity-service/src/tuple_store.rs",
        220,
    ),
    (
        "no-in-memory-durable-store",
        "crates/myelin-identity-service/src/pseudonym_store.rs",
        191,
    ),
    // MR-008 (SI-019/SI-020) ADDED the durable PG path for `RevocationStore` (`with_pg` over
    // `myelin_storage::DurableRevocationBacking` + the MR-022 `with_tenant_tx` convention) and PROVED
    // it durable (incl. expiry-across-restart) + tenant-isolated against live PG
    // (`integration_mr008_revocation_durable`). Same status as principal/tuple: the `Memory` enum
    // variant is still the always-compiled default and nothing wires `with_pg` yet → the
    // enum-following scanner STILL fires here (the struct header is at :193 after the MR-008-followup
    // instant-compare helper was added above it). Removed when production wires `with_pg` (MR-009).
    (
        "no-in-memory-durable-store",
        "crates/myelin-identity-service/src/revocation.rs",
        193,
    ),
    // `S7Denylist` (SI-020) — the machine-auth `authenticate` revocation CONSULT stub: a bare
    // `Arc<Mutex<BTreeSet<String>>>` of revoked jtis with NO durable backing (loses every revocation
    // on restart → a revoked token would validate again). MR-008 added it to the scanner's
    // NAMED_DURABLE_HOLDERS (it has no role suffix). It is NOT bound to PG (that would fork a second
    // revocation store); the fix is routing `CapabilityAuthenticator` through the now-durable
    // `RevocationStore` — an auth-path wiring change for MR-009 / the auth MRs. Fires until then.
    (
        "no-in-memory-durable-store",
        "crates/myelin-identity-service/src/machine_auth.rs",
        347,
    ),
    (
        "no-in-memory-durable-store",
        "crates/myelin-storage/src/kms.rs",
        470,
    ),
    (
        "no-in-memory-durable-store",
        "crates/myelin-storage/src/reserve_settle.rs",
        283,
    ),
    (
        "no-in-memory-durable-store",
        "crates/myelin-storage/src/restore_verify.rs",
        175,
    ),
    // -- closed false-negatives (verifier MR-004 review): alias / Vec / FsBlobStore / audit sink --
    (
        // `PseudonymErasureLedger` — field `inner: Arc<Mutex<LedgerByPartition>>` where the alias
        // `type LedgerByPartition = BTreeMap<…>` hid the collection from a literal-token scan
        // (census 10.8; must survive restore). → MR-007/009 (P-522/523).
        "no-in-memory-durable-store",
        "crates/myelin-identity-service/src/pseudonym_erase.rs",
        268,
    ),
    (
        // `InMemoryPostPitLedger` — field `records: Vec<ErasureRecord>` (hidden until `Vec<` was
        // added to the collection tokens). Post-restore re-erasure ledger. → P-ST-14 / P-522/523.
        "no-in-memory-durable-store",
        "crates/myelin-storage/src/reerase.rs",
        156,
    ),
    (
        // `FsBlobStore` — `objects: Mutex<HashMap<String, Vec<u8>>>`, `put()` just inserts (NO
        // `fs::write`). An in-memory store; its real byte backing is the Git/backup-durability track
        // (P-ST-30; census SI-014/015/029) — NOT the false "already byte-durable" premise.
        "no-in-memory-durable-store",
        "crates/myelin-storage/src/blob.rs",
        362,
    ),
    (
        // `MisrouteAudit` — `records: Arc<Mutex<Vec<MisrouteAuditRecord>>>`, an audit SINK whose
        // durable tamper-evident log is the named floor (census SI-028; control-plane durable MR).
        // MR-024 ADDED the durable PG sink (`myelin_storage::DurableMisrouteAuditBacking` +
        // `misroute_audit` table) + the binding (`DurablePlacementRegistry::record_misroute`), PROVEN
        // durable against live PG (`integration_mr024_placement_durable`). SUPPLEMENTED not removed:
        // the in-memory `MisrouteAudit` is still the default the gateway uses; the durable sink is
        // behind `integration` and production wiring (the gateway writing the durable audit) is MR-009.
        "no-in-memory-durable-store",
        "crates/myelin-control-plane/src/placement_of.rs",
        223,
    ),
    // ---- no-bare-tenant-pool (2) — MR-013 (P-531) ----
    (
        "no-bare-tenant-pool",
        "crates/myelin-storage/src/pg.rs",
        150,
    ),
    (
        "no-bare-tenant-pool",
        "crates/myelin-storage/src/pg.rs",
        413,
    ),
];

fn workspace_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(|p| p.parent())
        .expect("workspace root is two levels above the crate manifest dir")
        .to_path_buf()
}

fn collect_rs(dir: &Path, out: &mut Vec<PathBuf>) {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect_rs(&path, out);
        } else if path.extension().is_some_and(|e| e == "rs") {
            out.push(path);
        }
    }
}

fn all_src(root: &Path) -> Vec<PathBuf> {
    let mut out = Vec::new();
    let crates = root.join("crates");
    for c in std::fs::read_dir(&crates).expect("crates/ must exist").flatten() {
        let src = c.path().join("src");
        if src.is_dir() {
            collect_rs(&src, &mut out);
        }
    }
    out.sort();
    out
}

/// The live firing set across all three gates, as sorted `(scanner, crate-relative path, line)`.
fn live_violations(root: &Path) -> Vec<(String, String, usize)> {
    let mut out = Vec::new();
    let mut scanned = 0usize;
    for gate in gates() {
        let lint = (gate.lint)();
        for file in all_src(root) {
            let rel = file
                .strip_prefix(root)
                .unwrap()
                .to_string_lossy()
                .replace('\\', "/");
            // The lint crate's own scanners/fixtures carry the tokens as DATA; tests/fixtures hold
            // red samples. Excluded (named, like workspace_clean.rs).
            if rel.contains("myelin-lints/") || rel.contains("/tests/") || rel.contains("/fixtures/")
            {
                continue;
            }
            if !gate.scope.iter().any(|c| rel.contains(c)) {
                continue;
            }
            let src = std::fs::read_to_string(&file).expect("readable source file");
            for v in lint.run(&src) {
                out.push((v.lint.0.to_string(), rel.clone(), v.line));
            }
            scanned += 1;
        }
    }
    // Sanity: a 0-file scan would be a vacuous green (the un-wired-gate failure mode EI-01 §5).
    assert!(scanned >= 8, "expected to scan the spine src tree, scanned {scanned}");
    out.sort();
    out.dedup();
    out
}

#[test]
fn the_baseline_is_non_empty_and_internally_consistent() {
    // The baseline must be non-empty (a vacuous green would mean the scanners found nothing — an
    // un-wired gate). The counts pin the manifest shape.
    assert_eq!(BASELINE.len(), 24, "the committed baseline has 24 entries");
    let structural = BASELINE
        .iter()
        .filter(|(s, ..)| *s == "no-structural-crypto-in-prod")
        .count();
    let in_memory = BASELINE
        .iter()
        .filter(|(s, ..)| *s == "no-in-memory-durable-store")
        .count();
    let bare_pool = BASELINE
        .iter()
        .filter(|(s, ..)| *s == "no-bare-tenant-pool")
        .count();
    assert_eq!(structural, 5, "5 structural-crypto sites");
    assert_eq!(
        in_memory, 17,
        "17 in-memory durable-store sites: MR-007 re-pinned principal_store + tuple_store (durable \
         path added, Memory variant still the default → enum-following scanner still fires); MR-008 \
         added S7Denylist (machine_auth.rs) to the named holders + kept revocation.rs:173 (same \
         supplemented-not-removed status). All removed when MR-009 wires with_pg as the default."
    );
    assert_eq!(bare_pool, 2, "2 bare-tenant-pool sites");
    // The census-named anchor sites are present (the prompt's hard requirements).
    let has = |s: &str, p: &str, l: usize| BASELINE.contains(&(s, p, l));
    assert!(
        has(
            "no-structural-crypto-in-prod",
            "crates/myelin-identity-service/src/authenticate.rs",
            289
        ),
        "anchor authenticate.rs:289 must be in the baseline"
    );
    assert!(
        has("no-bare-tenant-pool", "crates/myelin-storage/src/pg.rs", 413),
        "anchor pg.rs:413 must be in the baseline"
    );
}

#[test]
fn the_production_graph_absence_ratchet_equals_the_committed_baseline() {
    let root = workspace_root();
    let live = live_violations(&root);
    let mut baseline: Vec<(String, String, usize)> = BASELINE
        .iter()
        .map(|(s, p, l)| (s.to_string(), p.to_string(), *l))
        .collect();
    baseline.sort(); // `live` is sorted; sort the manifest so the set-equality compare is order-free.

    // (a) A NEW violation that is NOT in the baseline → a NEW production-graph shortcut was
    //     introduced. FAIL LOUDLY: fix the code (do NOT add it to the baseline — the ratchet only
    //     tightens; a new shortcut must not be normalized into the manifest).
    let new: Vec<&(String, String, usize)> =
        live.iter().filter(|v| !baseline.contains(v)).collect();
    assert!(
        new.is_empty(),
        "NEW production-graph shortcut(s) introduced (loud, never swallowed — fix the code, do NOT \
         add to the baseline; the ratchet can only tighten toward zero):\n{}",
        new.iter()
            .map(|(s, p, l)| format!("  [{s}] {p}:{l}"))
            .collect::<Vec<_>>()
            .join("\n")
    );

    // (b) A baseline entry that NO LONGER fires → it was fixed (or its line moved). FAIL LOUDLY:
    //     remove (or re-pin) its baseline entry — the ratchet must record the tightening (this is
    //     exactly how MR-009/012/013 prove they removed a shortcut: they delete its entry here).
    let fixed: Vec<&(String, String, usize)> =
        baseline.iter().filter(|v| !live.contains(v)).collect();
    assert!(
        fixed.is_empty(),
        "baseline shortcut(s) FIXED or MOVED but still in the manifest (the ratchet tightens — \
         delete the removed entry, or re-pin a moved line):\n{}",
        fixed
            .iter()
            .map(|(s, p, l)| format!("  [{s}] {p}:{l}"))
            .collect::<Vec<_>>()
            .join("\n")
    );

    // Belt-and-braces: equal as sets (the two asserts above already imply this, stated explicitly).
    assert_eq!(
        live, baseline,
        "the live production-graph absence violation set must EQUAL the committed baseline"
    );
}
