//! # The production-graph ABSENCE baseline ratchet (MR-004) — the evidence-integrity skeleton.
//!
//! This test wires the three production-graph absence scanners
//! ([`myelin_lints::production_graph`]) two ways, in the same shape as the twelve architecture
//! lints' `fixture_matrix.rs` + `workspace_clean.rs`:
//!
//!   1. **The fixture matrix** — each scanner's RED fixture produces ≥1 violation (it bites) and
//!      its GREEN fixture produces 0 (it does not over-reject), and each red trips EXACTLY its own
//!      scanner (cross-isolation). This is the fixtures half (deterministic, hermetic).
//!
//!   2. **The baseline ratchet** — the scanners are run over the REAL `crates/*/src` tree and the
//!      violation set is asserted to EQUAL a committed baseline manifest of the CURRENT known
//!      shortcut sites — NOT zero. The real tree VIOLATES all three scanners by design (that is the
//!      whole point: they document the live shortcuts MR-009/MR-012/MR-013 will remove), so these
//!      three are deliberately NOT in `all_twelve()` / the `workspace_clean` zero-violation gate
//!      (adding them there would turn the build red). The ratchet can only TIGHTEN toward zero: it
//!      FAILS LOUDLY if (a) a NEW violation appears anywhere in scope, or (b) a baseline entry is
//!      fixed/moved but not removed from the manifest. That is the mechanism by which MR-009/012/013
//!      prove they actually removed the shortcut (EI-01 §5 — an uncommitted gate is no gate).
//!
//! ## Scope of each scanner's gate (documented, LOUD — never a silent skip; EI-01 §4)
//! Like `workspace_clean.rs`'s named exclusions, each scanner's WORKSPACE gate is scoped to where
//! its census-named shortcuts live, and the scope is named here, not hidden:
//!   - `no-structural-crypto-in-prod` → ALL crates. The `Structural*` mock-crypto types are few and
//!     the scanner is precise (construction-only, `#[cfg(test)]`-excluded), so a workspace-wide gate
//!     is clean and catches any prod construction wherever it appears.
//!   - `no-in-memory-durable-store` → the SPINE/SUBSTRATE crates (`myelin-identity-service`,
//!     `myelin-events`, `myelin-control-plane`, `myelin-storage`). Every census-named scanner-#2
//!     site lives here, and these are the crates MR-007/008/009 (the spine durable-persistence MRs
//!     this skeleton verifies) act on. Product-subsystem in-memory stores (chat/knowledge/issues/
//!     notif/agent/git/ci) ride their OWN subsystem tracks (census Section B2), not this SPINE
//!     scanner — scoping here keeps the baseline mapped to spine shortcuts and avoids flagging
//!     subsystem stores this MR does not own (scope discipline).
//!   - `no-bare-tenant-pool` → `myelin-storage` (the crate that owns the tenant RLS / pool
//!     primitive; census SI-005 = `pg.rs`). MR-013 (P-531) hardens THIS live pool.
//!
//! ## THE COMMITTED BASELINE MANIFEST (the current known-shortcut sites + their fixing MR/SI)
//! Each entry: `crate/path/file.rs:line — <scanner> — removed by MR-0XX (SI-0YY / P-NNN)`.
//! Generated by running the scanners over the real tree at MR-004. The line numbers are pinned;
//! when MR-009/012/013 edit a target file they update/remove its entry (the ratchet tightens).
//!
//! ### `no-structural-crypto-in-prod` (1) — MR-012 (P-528) flipped the 4 identity sites GREEN
//! MR-012 removed the mock `Structural*` crypto DEFAULTS from the identity-service production graph:
//!   - `authenticate.rs:289` (`StructuralVerifier` default, SI-004) — REMOVED. `HumanSsoAuthenticator::new`
//!     is now a `#[cfg(test)]` test-double; the production default is `HumanSsoAuthenticator::production`
//!     (the real `SchemeDispatchVerifier` whose fallback is `RefuseUnsupportedVerifier` — refuse-not-mock,
//!     SCIM + unwired schemes refuse, never mock).
//!   - `machine_auth.rs:403` (`StructuralTokenVerifier` default, SI-002) — REMOVED. `CapabilityAuthenticator::new`
//!     is now `#[cfg(test)]`; production injects the REAL `PasetoCapabilityVerifier` via `with_verifier`.
//!   - `mint.rs:253` / `mint.rs:265` (`StructuralTokenSigner` defaults, SI-003) — REMOVED. The two
//!     Structural-defaulting `RunTokenMinter` constructors are now `#[cfg(test)]`; the production minter
//!     (`StoreBackedCheck::with_index`) injects the REAL `PasetoCapabilitySigner` (Ed25519/PASETO v4) via
//!     `RunTokenMinter::with_signer_and_tuples`. Minted run tokens are now genuinely signed (a forged
//!     token is rejected); `StoreBackedCheck::introspect_run_token` round-trips them through the real verifier.
//! - `myelin-ci-controlplane/src/residency_drill.rs:444` — `StructuralAttestationVerifier` (SI-001 /
//!   attestation floor, P-527) — STAYS. This is the CI runner-ATTESTATION floor (a DIFFERENT subsystem
//!   from the auth spine); its removal belongs to the CI/attestation track, NOT this auth prompt. Left
//!   honestly in the baseline (the scanner stays at 1 remaining structural entry).
//!
//! ### `no-in-memory-durable-store` (9) — the spine durable-persistence waves (P-522/523)
//! - **MR-009b Wave 2 FLIPPED the 3 identity spine stores GREEN (17→14):**
//!   `principal_store.rs` `PrincipalStore` (SI-018), `tuple_store.rs` `TupleStore` (SI-019), and
//!   `revocation.rs` `RevocationStore` (SI-020) are now durable-by-default. Their in-memory
//!   `Memory(Arc<Mutex<Inner>>)` backend variant + `Inner` + the in-memory `::new()` constructors are
//!   `#[cfg(any(test, feature = "test-support"))]` TEST DOUBLES; the durable `Pg(..)`/`with_pg` path
//!   is the always-compiled PRODUCTION default (tokio/sqlx/myelin-config non-optional; `integration`
//!   is now a test-selector). The scanner strips the `test-support`-gated `Memory` variant, so the
//!   production backend enum presents POOL-ONLY → the three entries are REMOVED. Durable-by-default is
//!   proven live on PG (`integration_mr007/008/009/011`); DB-free unit tests use the doubles via the
//!   `myelin-identity-service/test-support` dev-dependency.
//!   (`machine_auth.rs:347 S7Denylist` SI-020 was an entry here; MR-011 DELETED the stub type and
//!   routed `CapabilityAuthenticator`'s revocation consult through the durable `RevocationStore`.)
//! - **MR-009b Wave 6a FLIPPED the 2 identity S2 pseudonym holders GREEN (11→9):**
//!   `pseudonym_store.rs` `PseudonymStore` (S2, SI-018 cluster) and `pseudonym_erase.rs`
//!   `PseudonymErasureLedger` (census 10.8) are now durable-by-default. Their in-memory backing
//!   (`Memory(Arc<Mutex<Inner>>)` for S2; `Memory(Arc<Mutex<LedgerByPartition>>)` for the ledger) +
//!   the `Inner` struct + the `LedgerByPartition` alias + the in-memory `::new()` constructors are
//!   `#[cfg(any(test, feature = "test-support"))]` TEST DOUBLES; the always-compiled PRODUCTION
//!   backend is the pool-backed `Pg(..)`/`with_pg` path over the MR-022 provider. S2 persists to the
//!   tightest-RLS `pseudonym_map` table (KMS-sealed real-identity link, ciphertext-only — the
//!   per-subject DEK stays in the KMS); the erasure ledger persists to the NON-shred-erasable, NO-RLS
//!   `identity_pseudonym_erasure_ledger` (10.8 — it must survive the crypto-shred it records + a
//!   restore so ID-D8 re-erasure can replay it). Backings + migrations (`0020`/`0021`/`0022`) live in
//!   `myelin_storage::pseudonym_durable`; the production `StoreBackedCheck::with_pg` composition root
//!   wires the durable pair (the in-memory pair is the `test-support`-gated double `with_index`
//!   wires). The scanner strips the `test-support`-gated `Memory` arms, so both production backend
//!   enums present POOL-ONLY → the two entries are REMOVED. Durable-by-default proven live on PG
//!   (`integration_mr009b_w6a_pseudonym_durable`); DB-free unit tests use the doubles via the
//!   `myelin-identity-service/test-support` dev-dependency.
//! - `myelin-events/src/outbox.rs:230`                    — `OutboxStore` in-mem (SI-007; events durable MR, P-522/523)
//! - **MR-009b Wave 3 FLIPPED the `DedupLedger` (SI-023) GREEN:** `dedup.rs` `DedupLedger` is now
//!   durable-by-default. The `Memory(Arc<Mutex<HashSet>>)` backend variant + its `Default` + the
//!   in-memory `::new()` constructor are `#[cfg(any(test, feature = "test-support"))]` TEST DOUBLES;
//!   the durable `Durable(Arc<dyn DurableDedup>)` arm is the always-compiled PRODUCTION default the
//!   events `serve()` composition root wires (`myelin_storage::events_serve::EventsRuntime::dedup_ledger`
//!   → `DedupLedger::durable`, backing `events_durable::DurableDedupBacking`). The scanner strips the
//!   `test-support`-gated `Memory` variant, so the production backend enum presents non-in-memory →
//!   the `dedup.rs:141` entry is REMOVED (13→12). Durable-by-default proven live on PG
//!   (`integration_mr023_events_serve`); the DB-free unit tests use the double via the
//!   `myelin-events/test-support` dev-dependency (the 3 in-process-floor consumer builders —
//!   chat `into_consumer`, `knowledge_app_spec_with_consumers`, `notif_app_spec_with_router` — now
//!   INJECT the ledger). NOTE — the SIBLING `outbox.rs:230` `OutboxStore` (SI-007) is NOT flipped in
//!   Wave 3: see the residual note in the module docs below (the outbox re-point is a separate wave).
//! - `myelin-events/src/reerase.rs:102`                   — `BusErasureLedger` in-mem (SI-039; GDPR/events durable MR)
//! - `myelin-control-plane/src/registry.rs:111`          — `Registry` placement in-mem (SI-011; cp durable MR)
//! - `myelin-control-plane/src/cross_cell_bridge.rs:244` — `CellResolverRegistry` in-mem (SI-052; cp/multi-cell MR)
//! - `myelin-control-plane/src/placement_of.rs:223`      — `MisrouteAudit` `Arc<Mutex<Vec<…>>>` audit sink (SI-028; cp durable MR)
//! - **MR-009b Wave 5 FLIPPED the `KmsEngine` (SI-006) GREEN (12→11):** `kms.rs` `KmsEngine` is now
//!   durable-by-default — a role struct over a `KmsBackend` enum (the Wave-2/DedupLedger pattern).
//!   The in-memory `Memory(KmsCore)` arm + `KmsEngine::new()`/`Default`/`from_root` are
//!   `#[cfg(any(test, feature = "test-support"))]` TEST DOUBLES; the always-compiled PRODUCTION
//!   backend is `Durable(kms_durable::DurableKms)` — the MR-025 software-sealed store hydrated at
//!   boot by `DurableKmsBacking::load_or_generate` (fail-closed + LOUD on a wrong/absent
//!   `MYELIN_KMS_SEAL_KEY` — never a fresh root that would orphan existing ciphertext), with EVERY
//!   mutation (`ensure_kek`/`ensure_dek`/`rotate_kek`/`destroy_kek`/`destroy_dek`) written through
//!   to `kms_wrapped_kek`/`kms_wrapped_dek`, so keys minted at runtime survive kill-9 too. The
//!   production boot root (edge `main.rs`) wires `load_or_generate` and exits non-zero on missing
//!   durable config — no silent in-memory fallback. The scanner strips the `test-support`-gated
//!   `Memory` arm, so the production-compiled named holder presents no in-memory backing — the
//!   `kms.rs:622` entry is REMOVED. Proven live: `integration_mr025_kms_durable`
//!   (decrypt-across-restart, wrong-seal-key-fails-closed, + the Wave-5 sync-API write-through
//!   restart proof). DB-free unit tests reach the double via `myelin-storage/test-support`.
//! - `myelin-storage/src/reserve_settle.rs:283`          — `CostLedger` reserve/settle in-mem (SI-021 cluster; MR-007/009)
//! - `myelin-storage/src/restore_verify.rs:175`          — `ErasureLedger` restore-verify in-mem (SI-036 cluster; P-530)
//! - `myelin-storage/src/reerase.rs:156`                  — `InMemoryPostPitLedger` `records: Vec<…>` (Vec false-negative closed; P-ST-14 / P-522/523)
//! - `myelin-storage/src/blob.rs:362`                     — `FsBlobStore` `Mutex<HashMap<…, Vec<u8>>>` IN-MEMORY (no `fs::write`); byte backing is the Git/backup track (P-ST-30; SI-014/015/029)
//!
//! ### RESIDUAL — `outbox.rs:230` `OutboxStore` (SI-007) is a SEPARATE, higher-coupling wave (NOT Wave 3)
//! MR-009b Wave 3 flipped the sibling `DedupLedger` (SI-023) but DELIBERATELY LEFT `OutboxStore` in
//! this baseline. Unlike `DedupLedger` (a role struct with a `backend` ENUM whose in-memory `Memory`
//! arm is gated behind `test-support` while the always-compiled `Durable` arm keeps the struct — and
//! every downstream `dedup: DedupLedger` field — compiling), the in-memory-ness of `OutboxStore` IS
//! the struct itself (`inner: Arc<Mutex<Inner>>`, no backend enum). To leave the baseline the whole
//! `OutboxStore`/`Inner`/`OutboxTransaction` must be `test-support`-gated — which removes the type
//! from the DEFAULT build and breaks EVERY production `outbox: OutboxStore` field/param across the
//! in-process event floor (`myelin-events` `relay.rs`/`reindex.rs`/`telemetry.rs`/`holder.rs`/
//! `reerase.rs` + `issues`/`git`/`flow`/`storage`/`substrate`/identity `tuple_store::write_tuples_pg`
//! …), none of which are dev-dep-fixable (they are production code) and none re-pointable to
//! `PgRelay::co_commit_in_tx` without threading a PG transaction through each emit site. The durable
//! outbox (`PgRelay`, already wired in `events_serve`) uses a co-commit-in-the-caller's-tx API that
//! CANNOT back `OutboxStore::begin/buffer/commit` without breaking the BUS-2 emit-iff-committed
//! guarantee, so the enum-variant trick that flipped `DedupLedger` does NOT transfer. Retiring the
//! in-process floor from production + the per-subsystem durable emit re-point is the MR-009 scope the
//! `events_serve.rs` module docs already name — tracked as its own wave, NOT folded into Wave 3.
//!
//! ### Role-suffix BLIND SPOT (documented coverage boundary — NOT yet gated; verifier MR-004 review)
//! Scanner #2 keys on the durable-role NAME suffix (`Store`/`Registry`/`Outbox`/`Ledger`) + a small
//! named-holder list (`KmsEngine`, `MisrouteAudit`). Census persistence shortcuts whose struct has
//! NEITHER are INVISIBLE to it — this baseline covers the role-suffix representative PER ORGAN, NOT
//! the full census persistence set. Known-uncovered (each rides a not-yet-authored persistence MR
//! that MUST extend this scanner — add the type to `NAMED_DURABLE_HOLDERS` or widen the suffix set —
//! when it lands; see the matching note in `production_graph.rs`):
//!   - `Consumer` (SI-024, events cursor/lag) · (S7Denylist SI-020 was here — DISCHARGED by MR-011)
//!   - `Firehose` (SI-037, live transport) · `InMemoryShredder` (SI-038, GDPR shred) ·
//!     `OltpPool` (SI-021, OLTP permit pool) · `PlacementService` stickiness (SI-026, control-plane)
//! A future "we made the bus / control-plane durable" claim is therefore only PARTIALLY gated until
//! that MR extends the scanner — this note exists so that gap is not silently relied upon.
//!
//! ### `no-bare-tenant-pool` (0) — MR-013 (P-531) flipped BOTH sites GREEN (census SI-005 closed)
//! The two former entries are REMOVED (the ratchet tightened 19 → 17):
//! - `myelin-storage/src/pg.rs:413` — session-scoped `set_config('myelin.tenant_id', $1, false)` —
//!   GONE. The PgStore tenant path (`put_tuple`/`reverse_index`/`check_tuple`/`list_objects` +
//!   `scoped_conn`/`*_in_region`) now sets the `(tenant, region)` GUC TRANSACTION-scoped
//!   (`set_config(.., true)`) via the MR-022 `with_tenant_tx` convention, so the GUC is discarded at
//!   COMMIT and NO tenant identity bleeds across a pooled checkout. `PgStore::connect` now builds the
//!   pool through `connect_pool_with_reset` (reset-on-release + region `application_name`).
//! - `myelin-storage/src/pg.rs:150` — bare raw-pool hatch `PgStore::pool() -> &PgPool` — GONE,
//!   replaced by `PgStore::health_check()` (the OLTP-reachability `SELECT 1` probe that does NOT hand
//!   out the raw pool). The integration tests build their OWN admin pool for throwaway-row cleanup
//!   (test infrastructure, not the tenant store handing out its pool). No named exclusion was needed.

use myelin_lints::production_graph::{
    no_bare_tenant_pool, no_in_memory_durable_store, no_structural_crypto_in_prod,
    production_graph_absence_scanners, PRODUCTION_GRAPH_ABSENCE_SCANNERS,
};
use myelin_lints::{Lint, LintId};
use std::path::{Path, PathBuf};

// ================================================================================================
// The fixture matrix (the fixtures half — each scanner red-bites + green-admits + cross-isolation).
// ================================================================================================

const FIXTURES_DIR: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/fixtures");

fn read_fixture(name: &str) -> String {
    let path = format!("{FIXTURES_DIR}/{name}");
    std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("missing fixture {path}: {e}"))
}

struct Row {
    lint: fn() -> Lint,
    id: LintId,
    red: &'static str,
    green: &'static str,
}

fn matrix() -> Vec<Row> {
    vec![
        Row {
            lint: no_structural_crypto_in_prod,
            id: LintId("no-structural-crypto-in-prod"),
            red: "no_structural_crypto_in_prod.red.rs.txt",
            green: "no_structural_crypto_in_prod.green.rs.txt",
        },
        Row {
            lint: no_in_memory_durable_store,
            id: LintId("no-in-memory-durable-store"),
            red: "no_in_memory_durable_store.red.rs.txt",
            green: "no_in_memory_durable_store.green.rs.txt",
        },
        Row {
            lint: no_bare_tenant_pool,
            id: LintId("no-bare-tenant-pool"),
            red: "no_bare_tenant_pool.red.rs.txt",
            green: "no_bare_tenant_pool.green.rs.txt",
        },
    ]
}

#[test]
fn the_matrix_covers_exactly_the_three_scanners() {
    let rows = matrix();
    assert_eq!(rows.len(), 3, "the matrix must cover all three absence scanners");
    let ids: Vec<LintId> = rows.iter().map(|r| r.id).collect();
    assert_eq!(ids, PRODUCTION_GRAPH_ABSENCE_SCANNERS.to_vec());
}

#[test]
fn every_red_fixture_bites() {
    for row in matrix() {
        let lint = (row.lint)();
        let v = lint.run(&read_fixture(row.red));
        assert!(
            !v.is_empty(),
            "scanner `{}` MUST reject its red fixture `{}`, but found 0 violations",
            row.id,
            row.red
        );
        assert!(
            v.iter().all(|x| x.lint == row.id),
            "scanner `{}` red-fixture violations must all carry its own id",
            row.id
        );
    }
}

#[test]
fn every_green_fixture_is_admitted() {
    for row in matrix() {
        let lint = (row.lint)();
        let v = lint.run(&read_fixture(row.green));
        assert!(
            v.is_empty(),
            "scanner `{}` MUST admit its green fixture `{}`, but found: {:?}",
            row.id,
            row.green,
            v
        );
    }
}

#[test]
fn each_red_fixture_trips_exactly_its_own_scanner() {
    // Cross-isolation among the three: a red fixture for scanner X is caught by X and by neither
    // of the other two (so the baseline-ratchet attributes each violation to the right scanner).
    let all = production_graph_absence_scanners();
    for row in matrix() {
        let red = read_fixture(row.red);
        let firing: Vec<LintId> = all
            .iter()
            .filter(|l| !l.run(&red).is_empty())
            .map(|l| l.id)
            .collect();
        assert_eq!(
            firing,
            vec![row.id],
            "red fixture `{}` must trip exactly `{}`, but tripped: {:?}",
            row.red,
            row.id,
            firing
        );
    }
}

// ================================================================================================
// MR-009b Wave 0 — the `test-support` cargo-feature gate is a TEST-DOUBLE gate (admit + bite).
//
// The in-memory durable-store DOUBLES are consumed CROSS-CRATE in non-test lib code, so they can't
// move to `#[cfg(test)]` (crate-local); they live behind a `test-support` cargo feature downstream
// crates enable as a DEV-dependency. Wave 0 teaches `no-in-memory-durable-store` that a
// `test-support`-gated in-memory store/backing is a test double (ADMITTED) — WITHOUT admitting any
// real production store (the un-gated twin still BITES). These two fixtures pin exactly that: the
// enhancement admits ONLY the test-support gate, never a real prod in-memory store. (Kept OUT of the
// 3-row `matrix()` above so the "exactly the three scanners" invariant is undisturbed.)
// ================================================================================================

#[test]
fn test_support_gate_admits_the_double_but_the_ungated_twin_still_bites() {
    // ADMIT: a `#[cfg(feature = "test-support")]` / `#[cfg(any(test, feature = "test-support"))]`
    // gated in-memory *Store (and its `Memory(Inner)` backend arm) is a test double — 0 violations.
    let green = read_fixture("no_in_memory_durable_store.test_support.green.rs.txt");
    let admitted = no_in_memory_durable_store().run(&green);
    assert!(
        admitted.is_empty(),
        "a `test-support`-gated in-memory store/backing is a TEST DOUBLE and must be ADMITTED, \
         but found: {admitted:?}"
    );

    // BITE (the over-broadening guard): the SAME shape with the gate REMOVED must STILL fire — if
    // this ever goes green, Wave 0 over-broadened and let a REAL production in-memory store through.
    let red = read_fixture("no_in_memory_durable_store.ungated.red.rs.txt");
    let bites = no_in_memory_durable_store().run(&red);
    assert!(
        !bites.is_empty(),
        "the UN-gated twin of the test-support fixture MUST still fire — Wave 0 must admit ONLY the \
         `test-support` gate, never a real prod in-memory store"
    );
    assert!(
        bites.iter().all(|v| v.lint == LintId("no-in-memory-durable-store")),
        "the un-gated fixture must fire ONLY the in-memory-durable-store scanner"
    );
}

// ================================================================================================
// The baseline ratchet (the live half — the scanners over the real tree vs the committed baseline).
// ================================================================================================

/// One scanner's workspace gate: its constructor + its scope (path substrings of the crates it
/// gates) — the documented, LOUD per-scanner scope (see the module docs).
struct Gate {
    lint: fn() -> Lint,
    scope: &'static [&'static str],
}

const SPINE: &[&str] = &[
    "crates/myelin-identity-service/",
    "crates/myelin-events/",
    "crates/myelin-control-plane/",
    "crates/myelin-storage/",
];

fn gates() -> Vec<Gate> {
    vec![
        Gate {
            lint: no_structural_crypto_in_prod,
            scope: &["crates/"], // ALL crates (precise, construction-only scanner).
        },
        Gate {
            lint: no_in_memory_durable_store,
            scope: SPINE, // the spine/substrate crates (census-named sites; MR-007/008/009).
        },
        Gate {
            lint: no_bare_tenant_pool,
            scope: &["crates/myelin-storage/"], // the tenant-pool primitive owner (SI-005; MR-013).
        },
    ]
}

/// THE COMMITTED BASELINE: `(scanner id, crate-relative path, 1-based line)`. Sorted. Mirrors the
/// annotated manifest in the module docs above. The ratchet asserts the live firing set EQUALS this.
const BASELINE: &[(&str, &str, usize)] = &[
    // ---- no-structural-crypto-in-prod (1) — MR-012 flipped the 4 identity sites GREEN ----
    // MR-012 (P-528) removed the `Structural*` mock-crypto DEFAULTS from the 4 identity-service
    // production constructors: `HumanSsoAuthenticator::new` (StructuralVerifier), `machine_auth`'s
    // `CapabilityAuthenticator::new` (StructuralTokenVerifier), and the two `RunTokenMinter`
    // constructors (StructuralTokenSigner). Those Structural constructors are now `#[cfg(test)]`
    // test-doubles; the production minter at `StoreBackedCheck::with_index` injects the REAL
    // `PasetoCapabilitySigner` (Ed25519/PASETO v4), and `HumanSsoAuthenticator::production` /
    // `CapabilityAuthenticator::with_verifier` wire the real refuse-not-mock dispatch. The 4 former
    // entries (authenticate.rs:289, machine_auth.rs:403, mint.rs:253, mint.rs:265) are GONE.
    // The single SURVIVING structural entry is the CI runner-attestation floor (a DIFFERENT
    // subsystem — P-527 attestation, not the auth spine), deferred to the CI track (see below).
    (
        "no-structural-crypto-in-prod",
        "crates/myelin-ci-controlplane/src/residency_drill.rs",
        444,
    ),
    // ---- no-in-memory-durable-store (7 here + 4 closed-false-negatives below = 11) ----
    //      spine durable-persistence waves (P-522/523); MR-009b Wave 2 flipped the 3 identity spine
    //      stores (principal/tuple/revocation) durable-by-default → removed (17→14); MR-009b Wave 3
    //      flipped the events `DedupLedger` (SI-023) durable-by-default → `dedup.rs:141` removed
    //      (in-memory count 13→12; total baseline 14→13); MR-009b Wave 5 flipped the `KmsEngine`
    //      (SI-006) durable-by-default → `kms.rs:622` removed (in-memory count 12→11; total 13→12).
    //      (The sibling `outbox.rs:230` `OutboxStore`/SI-007 STAYS — its durable re-point to
    //      `PgRelay::co_commit_in_tx` is a separate, higher-coupling wave; see the module-doc residual.)
    (
        "no-in-memory-durable-store",
        "crates/myelin-control-plane/src/cross_cell_bridge.rs",
        244,
    ),
    // MR-024 (SI-011) ADDED the durable PG path for the placement registry: the `cell` +
    // `tenant_placement` tables (frozen contract-12.3) + the HARD placement invariant as a REAL DB
    // TRIGGER (`myelin_storage::placement_durable`) + the `Pg | Memory` backend enum binding
    // (`myelin_control_plane::registry_durable::DurablePlacementRegistry::with_pg`), PROVEN durable +
    // trigger-enforced against live PG (`integration_mr024_placement_durable`). Same status as the
    // identity stores: the in-memory `Registry` (the `Memory` arm) is still the always-compiled
    // DEFAULT and nothing wires the Pg arm in production yet (the Pg arm is behind
    // `#[cfg(feature="integration")]`), so the in-memory store is still the production-graph default
    // and this entry STILL fires here — honestly, SUPPLEMENTED not removed. Removed when production
    // boot wires the durable Pg arm as the non-optional default (MR-009).
    (
        "no-in-memory-durable-store",
        "crates/myelin-control-plane/src/registry.rs",
        111,
    ),
    // `myelin-identity-service/src/pseudonym_store.rs:191` `PseudonymStore` (S2, SI-018 cluster) —
    // REMOVED by MR-009b Wave 6a (the `Memory(Arc<Mutex<Inner>>)` variant + `Inner` + `::new()` are
    // now `#[cfg(any(test, feature = "test-support"))]` test doubles; the always-compiled backend is
    // the pool-backed `Pg(PgPseudonymBacking)`/`with_pg` over the durable `pseudonym_map` table). The
    // production backend enum presents non-in-memory → the scanner no longer fires. See the
    // flipped-GREEN note in the module docs above.
    // `myelin-events/src/dedup.rs:141` `DedupLedger` (SI-023) — REMOVED by MR-009b Wave 3 (the
    // `Memory` variant + `::new()` + `Default` are now `#[cfg(any(test, feature = "test-support"))]`
    // test doubles; the always-compiled backend is the pool-backed `Durable(Arc<dyn DurableDedup>)`
    // arm the events `serve()` root wires). The production enum presents non-in-memory → the scanner
    // no longer fires. See the flipped-GREEN note in the module docs above.
    (
        "no-in-memory-durable-store",
        "crates/myelin-events/src/outbox.rs",
        230,
    ),
    (
        "no-in-memory-durable-store",
        "crates/myelin-events/src/reerase.rs",
        102,
    ),
    // MR-009b Wave 2 (SI-018/019/020) FLIPPED the S1 principal + S3 tuple + S7 revocation stores
    // GREEN: their in-memory `Memory(Arc<Mutex<Inner>>)` backend variant + `Inner` + the in-memory
    // `::new()` constructors are now `#[cfg(any(test, feature = "test-support"))]` TEST DOUBLES, and
    // the durable `Pg(..)`/`with_pg` path is the always-compiled PRODUCTION default (tokio/sqlx/
    // myelin-config non-optional; `integration` is now a test-selector). The PRODUCTION-compiled
    // backend enum presents POOL-ONLY (the scanner strips the `test-support`-gated `Memory` variant),
    // so `PrincipalStore`/`TupleStore`/`RevocationStore` no longer hold an in-memory collection in the
    // production graph — the three former entries (principal_store.rs:289, tuple_store.rs:220,
    // revocation.rs:193) are REMOVED (17→14). Durable-by-default is proven live on PG (mr007/008/009/
    // 011); the DB-free unit tests use the doubles via `test-support`. The S2 pseudonym store +
    // erasure ledger were flipped GREEN by MR-009b Wave 6a (their durable backings are now the
    // always-compiled default — see the flipped-GREEN notes above/below).
    // `S7Denylist` (SI-020) — REMOVED by MR-011 (the carried-forward fix is DISCHARGED). The
    // machine-auth `authenticate` revocation CONSULT was a bare `Arc<Mutex<BTreeSet<String>>>` of
    // revoked jtis with NO durable backing (lost every revocation on restart → a revoked token would
    // validate again). MR-011 ROUTES `CapabilityAuthenticator` through the durable `RevocationStore`
    // (the `(tenant, region)`-partitioned, `with_pg`-capable S7 store at revocation.rs:193, already in
    // this baseline) and DELETES the `S7Denylist` type. The machine-token revocation is now backed by
    // the SAME durable-capable store as every other revocation — the standalone tenant-less stub is
    // gone (proven cross-restart in `integration_mr011_machine_token_revocation_durable`). So this
    // entry is removed, not supplemented (the durable consult path is real now).
    // `myelin-storage/src/kms.rs` `KmsEngine` (SI-006) — REMOVED by MR-009b Wave 5 (the ratchet
    // tightened 12 → 11). The engine is now a role struct over a backend enum (`KmsBackend`,
    // the Wave-2/DedupLedger pattern): the in-memory `Memory(KmsCore)` arm + `KmsEngine::new()`/
    // `Default`/`from_root` are `#[cfg(any(test, feature = "test-support"))]` TEST DOUBLES, and the
    // always-compiled PRODUCTION backend is `Durable(DurableKms)` — the MR-025 software-sealed
    // store (`kms_durable::DurableKmsBacking::load_or_generate` over `kms_sealed_root`/
    // `kms_wrapped_kek`/`kms_wrapped_dek`, fail-closed + LOUD on a wrong/absent seal key) hydrating
    // the working set at boot, with EVERY mutation (`ensure_kek`/`ensure_dek`/`rotate_kek`/
    // `destroy_*`) writing through, so keys minted at runtime survive a kill-9 restart. The
    // production boot root (edge `main.rs`) wires `load_or_generate` and FAILS LOUD (exit non-zero)
    // on missing seal key / unreachable store — never a silent in-memory fallback. The scanner
    // strips the `test-support`-gated `Memory` arm, so the production-compiled named holder
    // presents no in-memory collection/backing. Durable-by-default proven live on PG
    // (`integration_mr025_kms_durable` — decrypt-across-restart + wrong-seal-key-fails-closed +
    // the Wave-5 write-through kill-9-equivalent proof); DB-free unit tests use the double via the
    // `myelin-storage/test-support` dev-dependency.
    (
        "no-in-memory-durable-store",
        "crates/myelin-storage/src/reserve_settle.rs",
        283,
    ),
    (
        "no-in-memory-durable-store",
        "crates/myelin-storage/src/restore_verify.rs",
        175,
    ),
    // -- closed false-negatives (verifier MR-004 review): Vec / FsBlobStore / audit sink --
    // (`PseudonymErasureLedger`, pseudonym_erase.rs:268 — the `type LedgerByPartition = BTreeMap<…>`
    //  ALIAS false-negative — was here; MR-009b Wave 6a FLIPPED it GREEN: the `Memory` arm + the
    //  `LedgerByPartition` alias + `::new()` are now `test-support`-gated test doubles, and the
    //  always-compiled backend is the pool-backed `Pg(PgErasureLedgerBacking)`/`with_pg` over the
    //  NON-shred-erasable, NO-RLS `identity_pseudonym_erasure_ledger` table (10.8 — it survives the
    //  crypto-shred it records + a restore). The production enum presents non-in-memory → removed.)
    (
        // `InMemoryPostPitLedger` — field `records: Vec<ErasureRecord>` (hidden until `Vec<` was
        // added to the collection tokens). Post-restore re-erasure ledger. → P-ST-14 / P-522/523.
        "no-in-memory-durable-store",
        "crates/myelin-storage/src/reerase.rs",
        156,
    ),
    (
        // `FsBlobStore` — `objects: Mutex<HashMap<String, Vec<u8>>>`, `put()` just inserts (NO
        // `fs::write`). An in-memory store; its real byte backing is the Git/backup-durability track
        // (P-ST-30; census SI-014/015/029) — NOT the false "already byte-durable" premise.
        "no-in-memory-durable-store",
        "crates/myelin-storage/src/blob.rs",
        362,
    ),
    (
        // `MisrouteAudit` — `records: Arc<Mutex<Vec<MisrouteAuditRecord>>>`, an audit SINK whose
        // durable tamper-evident log is the named floor (census SI-028; control-plane durable MR).
        // MR-024 ADDED the durable PG sink (`myelin_storage::DurableMisrouteAuditBacking` +
        // `misroute_audit` table) + the binding (`DurablePlacementRegistry::record_misroute`), PROVEN
        // durable against live PG (`integration_mr024_placement_durable`). SUPPLEMENTED not removed:
        // the in-memory `MisrouteAudit` is still the default the gateway uses; the durable sink is
        // behind `integration` and production wiring (the gateway writing the durable audit) is MR-009.
        "no-in-memory-durable-store",
        "crates/myelin-control-plane/src/placement_of.rs",
        223,
    ),
    // ---- no-bare-tenant-pool (0) — MR-013 (P-531) flipped BOTH sites GREEN ----
    // The two former entries (pg.rs:150 bare `pool() -> &PgPool` hatch, pg.rs:413 session-scoped
    // `set_config('myelin.tenant_id', $1, false)`) are GONE: MR-013 transaction-scoped the PgStore
    // tenant path through the MR-022 `with_tenant_tx` convention (`set_config(.., true)` inside a tx,
    // reset-on-release pool) and replaced the bare pool hatch with `PgStore::health_check()`. The
    // `no-bare-tenant-pool` scanner is now GREEN over the production tree (census SI-005 closed). No
    // named exclusion was needed — a real tenant store does not dodge the lint.
];

fn workspace_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(|p| p.parent())
        .expect("workspace root is two levels above the crate manifest dir")
        .to_path_buf()
}

fn collect_rs(dir: &Path, out: &mut Vec<PathBuf>) {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect_rs(&path, out);
        } else if path.extension().is_some_and(|e| e == "rs") {
            out.push(path);
        }
    }
}

fn all_src(root: &Path) -> Vec<PathBuf> {
    let mut out = Vec::new();
    let crates = root.join("crates");
    for c in std::fs::read_dir(&crates).expect("crates/ must exist").flatten() {
        let src = c.path().join("src");
        if src.is_dir() {
            collect_rs(&src, &mut out);
        }
    }
    out.sort();
    out
}

/// The live firing set across all three gates, as sorted `(scanner, crate-relative path, line)`.
fn live_violations(root: &Path) -> Vec<(String, String, usize)> {
    let mut out = Vec::new();
    let mut scanned = 0usize;
    for gate in gates() {
        let lint = (gate.lint)();
        for file in all_src(root) {
            let rel = file
                .strip_prefix(root)
                .unwrap()
                .to_string_lossy()
                .replace('\\', "/");
            // The lint crate's own scanners/fixtures carry the tokens as DATA; tests/fixtures hold
            // red samples. Excluded (named, like workspace_clean.rs).
            if rel.contains("myelin-lints/") || rel.contains("/tests/") || rel.contains("/fixtures/")
            {
                continue;
            }
            if !gate.scope.iter().any(|c| rel.contains(c)) {
                continue;
            }
            let src = std::fs::read_to_string(&file).expect("readable source file");
            for v in lint.run(&src) {
                out.push((v.lint.0.to_string(), rel.clone(), v.line));
            }
            scanned += 1;
        }
    }
    // Sanity: a 0-file scan would be a vacuous green (the un-wired-gate failure mode EI-01 §5).
    assert!(scanned >= 8, "expected to scan the spine src tree, scanned {scanned}");
    out.sort();
    out.dedup();
    out
}

#[test]
fn the_baseline_is_non_empty_and_internally_consistent() {
    // The baseline must be non-empty (a vacuous green would mean the scanners found nothing — an
    // un-wired gate). The counts pin the manifest shape.
    assert_eq!(
        BASELINE.len(),
        10,
        "the committed baseline has 10 entries (MR-009b Wave 2 flipped the 3 identity spine stores \
         GREEN: 17 → 14 — PrincipalStore/TupleStore/RevocationStore are durable-by-default, their \
         in-memory doubles `test-support`-gated; MR-009b Wave 3 flipped the events `DedupLedger` \
         (SI-023) — `dedup.rs:141` removed → 14 → 13; MR-009b Wave 5 flipped the `KmsEngine` \
         (SI-006) durable-by-default — `kms.rs:622` removed → 13 → 12; MR-009b Wave 6a flipped the 2 \
         identity S2 pseudonym holders (PseudonymStore + PseudonymErasureLedger) durable-by-default — \
         pseudonym_store.rs:191 + pseudonym_erase.rs:268 removed → 12 → 10)"
    );
    let structural = BASELINE
        .iter()
        .filter(|(s, ..)| *s == "no-structural-crypto-in-prod")
        .count();
    let in_memory = BASELINE
        .iter()
        .filter(|(s, ..)| *s == "no-in-memory-durable-store")
        .count();
    let bare_pool = BASELINE
        .iter()
        .filter(|(s, ..)| *s == "no-bare-tenant-pool")
        .count();
    assert_eq!(
        structural, 1,
        "1 structural-crypto site remains: MR-012 flipped the 4 identity sites GREEN (HumanSso/\
         Capability authenticators + the two RunTokenMinter constructors no longer build Structural*; \
         production injects the real PASETO signer / refuse-not-mock dispatch). The surviving entry is \
         the CI runner-attestation floor (residency_drill.rs, P-527) — a different subsystem, deferred \
         to the CI track."
    );
    assert_eq!(
        in_memory, 9,
        "9 in-memory durable-store sites: MR-009b Wave 2 FLIPPED the 3 identity spine stores \
         (PrincipalStore/TupleStore/RevocationStore) durable-by-default (16→13), MR-009b Wave 3 \
         FLIPPED the events `DedupLedger` (SI-023) durable-by-default (13→12), MR-009b Wave 5 \
         FLIPPED the `KmsEngine` (SI-006) durable-by-default (12→11), and MR-009b Wave 6a FLIPPED \
         the 2 identity S2 pseudonym holders — `PseudonymStore` (pseudonym_store.rs:191) + \
         `PseudonymErasureLedger` (pseudonym_erase.rs:268): their `Memory` arms + `Inner`/ \
         `LedgerByPartition` + `::new()` are now `test-support`-gated test doubles and the \
         always-compiled production backend is the pool-backed `Pg`/`with_pg` over the durable \
         `pseudonym_map` + non-shred-erasable `identity_pseudonym_erasure_ledger` tables the \
         production `StoreBackedCheck::with_pg` composition root wires (11→9). The remaining 9 \
         (events OUTBOX (SI-007, a separate higher-coupling wave) + reerase; control-plane \
         registry/bridge/misroute; storage reserve/restore/reerase/blob) flip in the later waves."
    );
    assert_eq!(
        bare_pool, 0,
        "0 bare-tenant-pool sites: MR-013 (P-531) closed both legs of census SI-005 — pg.rs's \
         session-scoped `set_config(<tenant GUC>, .., false)` is now TRANSACTION-scoped via the \
         MR-022 `with_tenant_tx` convention (no cross-checkout bleed), and the bare \
         `PgStore::pool() -> &PgPool` hatch is REMOVED (replaced by `health_check()`). The scanner \
         is GREEN over the production tree."
    );
    // The census-named anchor sites are present (the prompt's hard requirements).
    let has = |s: &str, p: &str, l: usize| BASELINE.contains(&(s, p, l));
    // MR-012 flipped the former auth-spine anchor (authenticate.rs:289) GREEN; the surviving
    // structural anchor is the CI runner-attestation floor (a different subsystem, deferred to the
    // CI track). It must still be present (honest: the scanner is not yet at zero).
    assert!(
        has(
            "no-structural-crypto-in-prod",
            "crates/myelin-ci-controlplane/src/residency_drill.rs",
            444
        ),
        "anchor residency_drill.rs:444 (the surviving CI attestation floor) must be in the baseline"
    );
    assert!(
        !has(
            "no-structural-crypto-in-prod",
            "crates/myelin-identity-service/src/authenticate.rs",
            289
        ),
        "authenticate.rs:289 was flipped GREEN by MR-012 and must NOT remain in the baseline"
    );
    assert!(
        !has("no-bare-tenant-pool", "crates/myelin-storage/src/pg.rs", 413)
            && !has("no-bare-tenant-pool", "crates/myelin-storage/src/pg.rs", 150),
        "the former anchors pg.rs:413 (session-scoped set_config) + pg.rs:150 (bare pool() hatch) \
         were flipped GREEN by MR-013 and must NOT remain in the baseline (the ratchet tightened)"
    );
}

#[test]
fn the_production_graph_absence_ratchet_equals_the_committed_baseline() {
    let root = workspace_root();
    let live = live_violations(&root);
    let mut baseline: Vec<(String, String, usize)> = BASELINE
        .iter()
        .map(|(s, p, l)| (s.to_string(), p.to_string(), *l))
        .collect();
    baseline.sort(); // `live` is sorted; sort the manifest so the set-equality compare is order-free.

    // (a) A NEW violation that is NOT in the baseline → a NEW production-graph shortcut was
    //     introduced. FAIL LOUDLY: fix the code (do NOT add it to the baseline — the ratchet only
    //     tightens; a new shortcut must not be normalized into the manifest).
    let new: Vec<&(String, String, usize)> =
        live.iter().filter(|v| !baseline.contains(v)).collect();
    assert!(
        new.is_empty(),
        "NEW production-graph shortcut(s) introduced (loud, never swallowed — fix the code, do NOT \
         add to the baseline; the ratchet can only tighten toward zero):\n{}",
        new.iter()
            .map(|(s, p, l)| format!("  [{s}] {p}:{l}"))
            .collect::<Vec<_>>()
            .join("\n")
    );

    // (b) A baseline entry that NO LONGER fires → it was fixed (or its line moved). FAIL LOUDLY:
    //     remove (or re-pin) its baseline entry — the ratchet must record the tightening (this is
    //     exactly how MR-009/012/013 prove they removed a shortcut: they delete its entry here).
    let fixed: Vec<&(String, String, usize)> =
        baseline.iter().filter(|v| !live.contains(v)).collect();
    assert!(
        fixed.is_empty(),
        "baseline shortcut(s) FIXED or MOVED but still in the manifest (the ratchet tightens — \
         delete the removed entry, or re-pin a moved line):\n{}",
        fixed
            .iter()
            .map(|(s, p, l)| format!("  [{s}] {p}:{l}"))
            .collect::<Vec<_>>()
            .join("\n")
    );

    // Belt-and-braces: equal as sets (the two asserts above already imply this, stated explicitly).
    assert_eq!(
        live, baseline,
        "the live production-graph absence violation set must EQUAL the committed baseline"
    );
}
